using Iedora.Dashboard;
using Iedora.Dashboard.Api;
using Iedora.Dashboard.Components;
using Iedora.Identity.Contracts;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Refit;

var builder = WebApplication.CreateBuilder(args);

builder.AddServiceDefaults(); // OpenTelemetry, health, resilience, service discovery

builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents();

// The admin logs into the dashboard itself with a cookie; the API JWT it obtains rides server-side
// (in the auth ticket), never in the browser. Anonymous requests are bounced to the login page.
builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
    .AddCookie(options =>
    {
        options.LoginPath = "/login";
        options.AccessDeniedPath = "/login";
        options.ExpireTimeSpan = TimeSpan.FromHours(8);
        options.SlidingExpiration = true;
        // Rotate the API access token (via /auth/refresh) shortly before it expires, on each request.
        options.Events = new CookieAuthenticationEvents { OnValidatePrincipal = TokenRefresh.OnValidatePrincipalAsync };
    });
// This is an admin console — [Authorize] (no named policy) requires the platform-admin role. Left as
// the DEFAULT (not fallback) policy so the anonymous /login page is still reachable.
builder.Services.AddAuthorizationBuilder()
    .SetDefaultPolicy(new AuthorizationPolicyBuilder()
        .RequireAuthenticatedUser().RequireRole(Roles.Admin).Build());
builder.Services.AddCascadingAuthenticationState();

// The typed API client (generated by Refitter from openapi/Iedora.Api.json). Its base address is the
// "api" resource resolved by Aspire service discovery; the bearer handler attaches the admin's token.
builder.Services.AddScoped<AccessToken>();
builder.Services.AddTransient<BearerHandler>();
builder.Services.TryAddSingleton(TimeProvider.System);
builder.Services.Configure<ApiAuthOptions>(builder.Configuration.GetSection(ApiAuthOptions.SectionName));

// Raw auth client: UseCookies=false so the API's HttpOnly refresh cookie is visible in Set-Cookie
// (AuthApi manages it per-admin). Separate from the Refit data client, which carries the bearer.
builder.Services.AddHttpClient<AuthApi>(c => c.BaseAddress = new Uri("https+http://api"))
    .ConfigurePrimaryHttpMessageHandler(() => new HttpClientHandler { UseCookies = false });

builder.Services.AddRefitClient<IIedoraApiv1>()
    .ConfigureHttpClient(c => c.BaseAddress = new Uri("https+http://api"))
    .AddHttpMessageHandler<BearerHandler>();

var app = builder.Build();

if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error", createScopeForErrors: true);
    app.UseHsts();
}
app.UseStatusCodePagesWithReExecute("/not-found", createScopeForStatusCodePages: true);
app.UseHttpsRedirection();
app.UseAuthentication();
app.UseAuthorization();
app.UseAntiforgery();

app.MapStaticAssets();
app.MapAuthEndpoints(); // POST /login, POST /logout (cookie sign-in / -out)
app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode();

app.Run();
