<Project Sdk="MSTest.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Framework.Web.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="ErrorOr" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Framework.Web\Framework.Web.csproj" />
  </ItemGroup>

</Project>
